### ISSUE TITLE
Home menu favorites

### ISSUE THREAD

**Issue by unlocKing** [pkscout/skin.estuary.leia.pkscout.mod#1]
Any chance you can add an option to use the saved favorites as home menu options?

Would be appreciated, cheers!

**Comment by pkscout** [comment]
Sorry, probably not. Because I’m not using any addons to providecthe more flexible main screen, it’s a fair amount of manual work that has to assume some finite things. Favorites are too amorphous and unpredictable to work with the way I’ve done this mod. You might the Estuary forum on the Kodi sites. I think there’s another mod that might do that.
